// Builds js/ui/icons.js from lucide-static SVGs (ISC licence).
// Usage: node tools/build-icons.mjs <path-to-lucide-static/icons>
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const NAMES = `sun sunrise sunset moon moon-star dumbbell footprints droplet droplets beef egg flame apple salad
bed bed-double brain book-open graduation-cap heart users user-round house briefcase target check circle-check
circle plus minus x chevron-right chevron-left chevron-down chevron-up search settings calendar calendar-days
chart-spline chart-column activity ruler scale camera image pencil trash-2 archive archive-restore undo-2 download
upload bell bell-off eye eye-off timer clock play square list-checks layout-grid grip-vertical trophy medal flag
compass church hand-heart heart-handshake message-circle coffee smile meh frown battery-low battery-full zap leaf
pill sparkle sparkles info circle-alert shield-check lock share square-plus ellipsis arrow-up-right arrow-down-right
arrow-right trending-up trending-down move-right refresh-cw wifi-off smartphone monitor sun-moon notebook-pen
feather lightbulb focus hourglass power repeat person-standing bike shirt utensils chef-hat wallet milk wheat
glass-water scan-eye book-heart baby armchair layers orbit circle-dot gauge star move file-json file-spreadsheet
hard-drive-download database history list sliders-horizontal palette alarm-clock flower-2 sprout heart-pulse
thermometer log-out sofa scroll-text tally-5 rotate-ccw ellipsis-vertical hand ear list-todo map calendar-check`.split(/\s+/).filter(Boolean);

const dir = process.argv[2];
if (!dir) throw new Error('Pass the lucide-static icons directory');
const out = {};
for (const name of NAMES) {
  const svg = readFileSync(join(dir, `${name}.svg`), 'utf8');
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s*\n\s*/g, '')
    .replace(/\s\/>/g, '/>');
  out[name] = inner;
}

// The icons Today needs at first render go in icons.js; the rest load right after, from icons-more.js.
const CORE = new Set(`bed calendar chart-spline check chevron-down chevron-right droplet ellipsis footprints grip-vertical map moon notebook-pen orbit plus repeat sliders-horizontal star sun sunrise user-round utensils circle x chevron-left chevron-up minus activity hand-heart book-heart person-standing power heart house eye moon-star sparkles circle-alert list-todo trash-2 search beef dumbbell scale`.split(' '));
const pick = (keep) => Object.fromEntries(Object.entries(out).filter(([n]) => CORE.has(n) === keep));
const fmt = (o) => JSON.stringify(o, null, 0).replace(/","/g, '",\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, '\n}');

const here = dirname(fileURLToPath(import.meta.url));
const body = `// Generated by tools/build-icons.mjs from lucide-static (ISC licence). Do not edit by hand.
// The icons Today needs are here; the rest (icons-more.js) load right after the first screen.
import { raw } from './dom.js';

const PATHS = ${fmt(pick(true))};

let more = null;
/** Load the remaining icons (once). Screens other than Today wait for them; Today redraws when they land. */
export const loadIcons = () => (more ||= import('./icons-more.js').then((m) => { Object.assign(PATHS, m.PATHS); }));
export const hasIcon = (name) => name in PATHS;

export function icon(name, { size = 20, stroke = 1.75, cls = '', label } = {}) {
  const inner = PATHS[name] || PATHS.circle;
  const a11y = label ? \`role="img" aria-label="\${label}"\` : 'aria-hidden="true"';
  return raw(\`<svg class="ic \${cls}" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="\${stroke}" stroke-linecap="round" stroke-linejoin="round" \${a11y} focusable="false">\${inner}</svg>\`);
}
`;
writeFileSync(join(here, '..', 'js', 'ui', 'icons.js'), body);
writeFileSync(join(here, '..', 'js', 'ui', 'icons-more.js'), `// Generated by tools/build-icons.mjs from lucide-static (ISC licence). Do not edit by hand.
// Icons that Today doesn't need at first render; icons.js loads them right after.
export const PATHS = ${fmt(pick(false))};
`);
console.log(`icons: ${NAMES.length} (${CORE.size} at first render)`);
